### ISSUE TITLE
Hot or Not Feed

### ISSUE THREAD

**Issue by harsh-yral** [go-bazzinga/hot-or-not-backend-canister#5]
Backend:
- [x] go-bazzinga/hot-or-not-dapp#762
- [ ] go-bazzinga/hot-or-not-backend-canister#91

Frontend:
- [x] go-bazzinga/hot-or-not-dapp#786

# Features

## Possible Denominations:
- 10
- 50
- 100

## Other
- 1 hour slots
- 100 participants in each slot
- 48 total slots - post runs slots for a period of 2 days/48 hours

# Outcome
- Equal hot or not - All participating tokens get burnt
- Voted on winning side - Double amount of tokens won
- Voted on losing side - Staked tokens burnt
